version: '3.8'

services:
  saros-db:
    container_name: saros-db
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_DB: saros-db
      POSTGRES_USER: ${SAROS_DB_USERNAME}
      POSTGRES_PASSWORD: ${SAROS_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-saros:/var/lib/postgresql/saros/data
    networks:
      - saros-network

volumes:
  db-saros:
    driver: local

networks:
  saros-network: